name: Script to convert all audio files of a directory to mp3
# Usage: automatix convert_mp3.yaml --vars directory="/some/directory" 
vars:
  directory: PATH_TO_DIRECTORY
pipeline:
  - files=local: find "{directory}" -type f | grep -v .mp3 | grep -v .rtf | grep -v .pdf
  - files?backup=local: mktemp -d | tr -d '\n'
  - files?local: rsync -zaXAP "{directory}" {backup}/
  - files?commands=local: echo "{files}" | awk -F . 'NF {{print "ffmpeg -y -i \""$0"\" \""$0".mp3\""}}'
  - files?local: '{commands}'
  - files?commands=local: echo "{files}" | awk -F . 'NF {{print "rm \""$0"\""}}'
  - files?local: '{commands}'
cleanup:
  - files?manual: You can remove the backup folder at {backup}.
